[build]
  # empty build command
  command = "#"

  # location of config files
  base = "/"

  # files hosted on Netlify (path relative to base)
  publish = "static/"

  # Netlify Functions (path relative to base)
  functions = "functions/"

  environment = {AWS_LAMBDA_JS_RUNTIME = "nodejs12.x"}
